spring.application.name=leaderless
server.port=${SERVER_PORT:8080}

# will be overridden at runtime
self.url=${SELF_URL:http://localhost:8080}
peers=${PEERS:http://localhost:8081}

# Leaderless Replication Settings

# Delay (in milliseconds) to simulate follower processing time
# when handling propagation requests.
follower.handler.delay.ms=100

# Delay (in milliseconds) to simulate data writing time in database
# when handling propagation requests.
coordinator.post.peer.sleep.ms=200

# Maximum retry time when propagation fail
max.retries=5

# Timeout (in milliseconds) for the coordinator when waiting
# for all peers to acknowledge propagation.
propagation.timeout.ms=5000