spring.application.name=warehouse-service
server.port=8080

# This is the queue our listener will check
spring.rabbitmq.queue=warehouse_orders

# RabbitMQ Connection Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# Configure the listener for manual acknowledgment
spring.rabbitmq.listener.simple.acknowledge-mode=manual

# Multithreaded consumers configuration
spring.rabbitmq.listener.simple.concurrency=${LISTENER_CONCURRENCY:10}
spring.rabbitmq.listener.simple.prefetch=100

# Actuator
# Expose health and info endpoints
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
# The default path is /actuator, so health is at /actuator/health