server.port=8081
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
spring.application.name=shopping-cart-service

# RabbitMQ Connection Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# Messages Queue Configuration
rabbitmq.queue.name=${RABBITMQ_QUEUE_NAME:warehouse_orders}
spring.rabbitmq.mqChannelSize=${RABBITMQ_MQ_CHANNEL_SIZE:25}
spring.rabbitmq.mqConnectionLimit=${RABBITMQ_MQ_CONNECTION_LIMIT:25}

spring.rabbitmq.publisher-confirm-type=none
spring.rabbitmq.publisher-returns=false

# Enable batching in the template.
spring.rabbitmq.template.batch.enabled=true

# The number of messages to batch together.
spring.rabbitmq.template.batch.batch-size=100

# The max size in bytes (e.g., 128KB) to batch.
# Whichever limit is hit first (size or bytes) triggers the send.
spring.rabbitmq.template.batch.buffer-limit=131072

# How long to wait (in ms) before sending an incomplete batch.
# e.g., if you only have 20 messages, it will send them after 50ms.
spring.rabbitmq.template.batch.timeout=50

# Actuator
# Expose health and info endpoints
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
# The default path is /actuator, so health is at /actuator/health

# auth service url
auth.service.url=${AUTH_SERVICE_URL:localhost:8070}

# warehouse service url
warehouse.service.url=http://localhost:8080