#server configuration

server.port=${PORT:8070}
server.servlet.context-path=/

#Logging configuration
logging.level.com.cs6650.a3creditcardservice=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Application info (useful for monitoring)
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.application.name=a3-CreditCard-service

# Actuator
# Expose health and info endpoints
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always